/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.bristermitten.java2haskell;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        final var code = """
                import Control.Monad
                main = do
                    i <- readLn :: IO Int
                    replicateM_ i (putStrLn "Hello World")
                """;

        CodeExecutor.execute(code);
    }
}
