/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.bristermitten.java2haskell;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        final var code = """
                import Control.Monad
                main = replicateM_ 5 (putStrLn "Hello World")
                """;

        var output = CodeExecutor.execute(code);

        System.out.println(output);
    }
}
